In [16]:
import numpy

X = numpy.random.rand(5,5)
Z = (X -numpy.mean(X)) / numpy.std(X)
print(X)

numpy.save('X_normalized.npy', X)
print("X_normalized.npy:")
print(X)

loaded_X = numpy.load('X_normalized.npy')
print("\nLoaded :")
print(loaded_X)

[[0.25410321 0.13840081 0.62450594 0.34041826 0.72367044]
 [0.11715589 0.5483353  0.56923695 0.61447249 0.84205148]
 [0.84131915 0.69864619 0.94135864 0.48760745 0.75616875]
 [0.10692745 0.81176861 0.69942624 0.09046091 0.55533871]
 [0.9005241  0.12914661 0.85073979 0.69703331 0.32959194]]
Original Matrix X:
[[0.25410321 0.13840081 0.62450594 0.34041826 0.72367044]
 [0.11715589 0.5483353  0.56923695 0.61447249 0.84205148]
 [0.84131915 0.69864619 0.94135864 0.48760745 0.75616875]
 [0.10692745 0.81176861 0.69942624 0.09046091 0.55533871]
 [0.9005241  0.12914661 0.85073979 0.69703331 0.32959194]]

Loaded Matrix X from matrix_X.npy:
[[0.25410321 0.13840081 0.62450594 0.34041826 0.72367044]
 [0.11715589 0.5483353  0.56923695 0.61447249 0.84205148]
 [0.84131915 0.69864619 0.94135864 0.48760745 0.75616875]
 [0.10692745 0.81176861 0.69942624 0.09046091 0.55533871]
 [0.9005241  0.12914661 0.85073979 0.69703331 0.32959194]]


In [24]:
import numpy

A = numpy.arange(1,101) ** 2
A = A.reshape(10,10)
print(A)

div_by_3 = A[A % 3 == 0]
div_by_3 = div_by_3.reshape(3,11)

print("\nThese are the following elements that are divisible by 3 \n" , div_by_3)

numpy.save('div_by_3.npy', div_by_3)
loaded_div_by_3 = numpy.load('div_by_3.npy')
print("\nLoaded data from div_by_3.npy:")
print(loaded_div_by_3)

[[    1     4     9    16    25    36    49    64    81   100]
 [  121   144   169   196   225   256   289   324   361   400]
 [  441   484   529   576   625   676   729   784   841   900]
 [  961  1024  1089  1156  1225  1296  1369  1444  1521  1600]
 [ 1681  1764  1849  1936  2025  2116  2209  2304  2401  2500]
 [ 2601  2704  2809  2916  3025  3136  3249  3364  3481  3600]
 [ 3721  3844  3969  4096  4225  4356  4489  4624  4761  4900]
 [ 5041  5184  5329  5476  5625  5776  5929  6084  6241  6400]
 [ 6561  6724  6889  7056  7225  7396  7569  7744  7921  8100]
 [ 8281  8464  8649  8836  9025  9216  9409  9604  9801 10000]]

These are the following elements that are divisible by 3 
 [[   9   36   81  144  225  324  441  576  729  900 1089]
 [1296 1521 1764 2025 2304 2601 2916 3249 3600 3969 4356]
 [4761 5184 5625 6084 6561 7056 7569 8100 8649 9216 9801]]

Loaded data from div_by_3.npy:
[[   9   36   81  144  225  324  441  576  729  900 1089]
 [1296 1521 1764 2025 2304 2601 2916 3249 36